/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabajopractico4.interfaz;

import java.util.HashSet;
import trabajopractico4.Alumno;
import trabajopractico4.Materia;

/**
 *
 * @author Emiliano
 */
public class Formulario extends javax.swing.JFrame {
 public static HashSet<Alumno> listaAlumnos = new HashSet<>();
    public static HashSet<Materia> listaMaterias = new HashSet<>();
    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemAlumno = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        itemMateria = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        itemInscrpcion = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();
        itemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(51, 51, 255));
        escritorio.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );

        jMenu1.setText("Alumno");

        itemAlumno.setText("Agregar Alumno");
        itemAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAlumnoActionPerformed(evt);
            }
        });
        jMenu1.add(itemAlumno);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Materia");

        itemMateria.setText("Agregar Materia");
        itemMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMateriaActionPerformed(evt);
            }
        });
        jMenu4.add(itemMateria);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Registro");

        itemInscrpcion.setText("Inscripcion");
        itemInscrpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInscrpcionActionPerformed(evt);
            }
        });
        jMenu5.add(itemInscrpcion);

        jMenuBar1.add(jMenu5);

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });

        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        menuSalir.add(itemSalir);

        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        
    }//GEN-LAST:event_menuSalirActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemSalirActionPerformed

    private void itemMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMateriaActionPerformed
       formularioMaterias materia=new formularioMaterias();
       materia.setVisible(true);
       escritorio.add(materia);
       escritorio.moveToFront(materia);
    }//GEN-LAST:event_itemMateriaActionPerformed

    private void itemInscrpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInscrpcionActionPerformed
       formularioInscripcion inscripcion = new formularioInscripcion();
       inscripcion.setVisible(true);
       escritorio.add(inscripcion);
       escritorio.moveToFront(inscripcion);
    }//GEN-LAST:event_itemInscrpcionActionPerformed

    private void itemAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAlumnoActionPerformed
       formularioAlumno alumno=new formularioAlumno();
       alumno.setVisible(true);
       escritorio.add(alumno);
       escritorio.moveToFront(alumno);
    }//GEN-LAST:event_itemAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem itemAlumno;
    private javax.swing.JMenuItem itemInscrpcion;
    private javax.swing.JMenuItem itemMateria;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuSalir;
    // End of variables declaration//GEN-END:variables
}
